version: 1.0.{build}
assembly_info:
  patch: false
platform: Any CPU
configuration:
  - Debug
  - Release
  
branches:
  except:
    - /^diadocsdk-csharp-v/

environment:
  diadoc_signing_secret:
    secure: anZ3SPfv+ZQGxXQdwHzCqwo0sKmdAVySXJr6j8sDIcuUjFqit9n1V+Va+UG+dIw8

build_script:
- ps: .\build.ps1 -Target "AppVeyor" -Configuration $env:configuration -Verbosity Diagnostic

deploy:
  - provider: GitHub
    release: $(appveyor_repo_tag_name)
    description: 'diadocsdk-csharp'
    auth_token:
      secure: zLJKfCFYSNM3Pv10x3js66vH7RiA0D/C9Ww5uymd5IntAzthBnehqYqQNpDvnLnf # encrypted token from GitHub
    artifact: diadocsdk-csharp-binaries.zip;/\.nupkg$/
    draft: false
    prerelease: false
    on:
      branch: master                 # release from master branch only
      configuration: Release         # deploy release configuration
      appveyor_repo_tag: true        # deploy on tag push only
      appveyor_repo_tag_name: /^versions/

  - provider: NuGet
    api_key:
      secure: F+bjpuFNMVyN4NbLTkgSbv2axvB22iSw12XLUGXMHBDpEAM7wjktM/j8AYRcoQm5
    skip_symbols: true
    artifact: /\.nupkg$/
    on:
      branch: master                 # release from master branch only
      configuration: Release         # deploy release configuration
      appveyor_repo_tag: true        # deploy on tag push only
      appveyor_repo_tag_name: /^versions/
