version: 1.0.{build}
assembly_info:
  patch: false
platform: Any CPU
configuration:
  - Debug
  - Release
  
environment:
  diadoc_signing_secret:
    secure: prJOj46LFF9HWKRH4PZ8vSS7wgSkkAFIkSCkfqWfAoPNGhUcYqplF4h4PyxEmMjb

build_script:
- ps: .\build.ps1 -Target "AppVeyor" -Configuration $env:configuration -Verbosity Diagnostic

deploy:
  - provider: GitHub
    release: $(appveyor_repo_tag_name)
    description: 'diadocsdk-csharp'
    auth_token:
      secure: BSnVMByuW1RN2cKD//7Y2+RRjsmhSfgBd2QK7IpyAadKDh8dIsYe4MF9bvX0SnEz # encrypted token from GitHub
    artifact: diadocsdk-csharp-binaries.zip;/\.nupkg$/
    draft: false
    prerelease: false
    on:
      branch: master                 # release from master branch only
      configuration: Release         # deploy release configuration
      appveyor_repo_tag: true        # deploy on tag push only
      appveyor_repo_tag_name: /^versions/

  - provider: NuGet
    api_key:
      secure: F+bjpuFNMVyN4NbLTkgSbv2axvB22iSw12XLUGXMHBDpEAM7wjktM/j8AYRcoQm5
    skip_symbols: true
    artifact: /\.nupkg$/
    on:
      branch: master                 # release from master branch only
      configuration: Release         # deploy release configuration
      appveyor_repo_tag: true        # deploy on tag push only
      appveyor_repo_tag_name: /^versions/
