version: 1.36.{build}
assembly_info:
  patch: false
platform: Any CPU
configuration:
  - Debug
  - Release

environment:
  diadoc_signing_secret:
    secure: anZ3SPfv+ZQGxXQdwHzCqwo0sKmdAVySXJr6j8sDIcuUjFqit9n1V+Va+UG+dIw8

build_script:
- ps: .\build.ps1 -Target "AppVeyor" -Configuration $env:configuration -Verbosity Diagnostic

deploy:
  release: diadocsdk-csharp-v$(appveyor_build_version)
  description: 'diadocsdk-csharp'
  provider: GitHub
  auth_token:
    secure: zLJKfCFYSNM3Pv10x3js66vH7RiA0D/C9Ww5uymd5IntAzthBnehqYqQNpDvnLnf # encrypted token from GitHub
  artifact: diadocsdk-csharp-binaries.zip;/\.nupkg$/
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    configuration: Release         # deploy release configuration
    appveyor_repo_tag: true        # deploy on tag push only